# Database and secrets
slick.dbs.default.driver = "slick.driver.SQLiteDriver$"
slick.dbs.default.db.driver   = "org.sqlite.JDBC"
slick.dbs.default.db.url      = ${?DATABASE_URL}
play.evolutions.enabled        = true
play.evolutions.autoApply      = true
play.http.secret.key           = ${?PLAY_HTTP_SECRET_KEY}

# Serve only HTTP; Traefik will terminate TLS
play.server {
  http {
    port = ${?PORT}    # default 9000
  }
  https {
    port = -1
  }
}

# Disable automatic HTTP→HTTPS redirects
play.filters.enabled -= play.filters.https.RedirectHttpsFilter