name: Publish to GHCR
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        # e.g. refs/tags/v1.2.3 -> 1.2.3
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/blog-motor:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/blog-motor:latest
    
      - name: Verify pushed tags
        run: |
          echo "Pushed image tags:"
          echo " - ghcr.io/${{ github.repository_owner }}/blog-motor:${{ env.VERSION }}"
          echo " - ghcr.io/${{ github.repository_owner }}/blog-motor:latest"
