name: Publish to GHCR
on:
  push:
    branches: [ main ]
    tags: -'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
    
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/blog-motor:${{ github.ref_name#v }}
            ghcr.io/${{ github.repository_owner }}/blog-motor:latest
    
      - name: Output pushed tag
        run: echo "Pushed ghcr.io/${{ github.repository_owner }}/blog-motor:${{ env.VERSION }}"
