name: Publish to GHCR
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version and metadata
        id: meta
        run: |
          # Default to git SHA for branch pushes
          VERSION=$(git rev-parse --short HEAD)
          TAGS="ghcr.io/${{ github.repository_owner }}/blog-motor:sha-${VERSION}"

          # If this is a tag push, extract semantic version
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f1,2)

            TAGS="ghcr.io/${{ github.repository_owner }}/blog-motor:${VERSION}"
            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/blog-motor:${MINOR}"
            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/blog-motor:${MAJOR}"
            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/blog-motor:latest"
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/blog-motor:latest"
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./blog-motor
          file: ./blog-motor/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.TAGS }}

      - name: Output pushed tags
        run: |
          echo "Pushed tags:"
          echo "${{ steps.meta.outputs.TAGS }}" | tr ',' '\n'
